name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull muhammadaslam2003/bookatserver:latest

      - name: Delete older Containers
        run: sudo docker rm -f bookatserver-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8000:8000 --name bookatserver-container muhammadaslam2003/bookatserver
