name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "SOCKET_PORT=${{ secrets.SOCKET_PORT }}" >> .env          
          echo "FRONT_END=${{ secrets.FRONT_END }}" >> .env          
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env          
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env          
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env          
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
          echo "TWILIO_VERIFY_SID=${{ secrets.TWILIO_VERIFY_SID }}" >> .env
          echo "NODEMAILER_USER_EMAIL=${{ secrets.NODEMAILER_USER_EMAIL }}" >> .env
          echo "NODEMAILER_PASS=${{ secrets.NODEMAILER_PASS }}" >> .env

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t muhammadaslam2003/bookatserver:latest .

      - name: Push to Dockerhub
        run: docker push muhammadaslam2003/bookatserver:latest
